#!/usr/bin/perl

# print "Input filename: ";
# $filename = <stdin>;

$filename = "class.txt";
chomp($filename);
# ($outfile) = split /\./, $filename;
$outfile = "temp1.out";
open(IN, $filename);
open(OUT, ">".$outfile);
$total = 0;

while(<IN>){
	$line = $_;
	chomp($line);
($ssn,$lname,$fname,$l1,$l2,$l3,$l4,$l5,$l6,$l7,$l8,$l9,$l10,$l11,$l12,$l13,$l14,$l15,$l16,$l17,$l18,$l19,$l20,$l21,$l22,$l23,$l24)=split ' ', $line;

#	$ssn = substr($ssn,5,8);
        print OUT "$ssn\t";
	print OUT "$l1\t";
	print OUT "$l2\t";
	print OUT "$l3\t";
	print OUT "$l4\t";
	print OUT "$l5\t";
	print OUT "$l6\t";
	print OUT "$l7\t";
	print OUT "$l8\t";
#	print OUT "$l9\t";
#	print OUT "$l10\t";
	print OUT "$l11\t";
	print OUT "$l12\t";
	print OUT "$l13\t";
	print OUT "$l14\t";
	print OUT "$l15\t";
	print OUT "$l16\t";
#	print OUT "$l17\t";
#	print OUT "$l18\t";
	print OUT "$l19\t";
	print OUT "$l20\t";
	print OUT "$l21\t";
	print OUT "$l22\t";
	print OUT "$l23\t";
	print OUT "$l24\n";
	$total++;
}

close(OUT);
close(IN);
system "sort -n temp1.out > temp2.out";
system "pr -e3 -t temp2.out  > grades.txt";
system "echo 'STUDENTS: ' >> grades.txt";
system "cat class.txt | wc -l >> grades.txt";
system "mv grades.txt \.\.";
system "rm temp1.out temp2.out";
print "Done.";
