<html>
<title>CS 350 PHP Lab Solution</title>
<body>
<table border=1 cellpadding=2 cellspacing=0>
<tr>
   <td>Name:</td><td>samantha spade</td>
</tr>
<tr>
   <td>Course:</td><td>cs350: Programming Languages</td>
</tr><tr>
   <td>Lab #:</td><td>PHP Lab</td>
</tr>
</table>
<hr>
<?php
   parse('data.xml');
   echo "<H3>Inventory List</H3><pre>";
   dump_array();
   report(); 
//----------------------------------------------------------------------------
// setup variables, open file, create a parser object and event handlers
function parse($filename)
{
     global $n_items;
     $n_items = 0;
      
     $xml_parser = xml_parser_create();
     
     // set handler for start and end tags   
     xml_set_element_handler($xml_parser, "XML_startElement","XML_endElement");

     // set handler for character data between tags
     xml_set_character_data_handler($xml_parser, "XML_data");

     if( !($fp = fopen($filename, 'r')) ) {
            die("could not open XML input");
     }

     // read 4096 bytes at a time
     while($data = fread($fp, 4096))
     {
        // parse the file
        if ( !xml_parse ( $xml_parser, $data, feof($fp) ) )
        {
          die(sprintf("XML error: %s at line %d",
          xml_error_string(xml_get_error_code($xml_parser)),
          xml_get_current_line_number($xml_parser)));
        }
     }
     xml_parser_free($xml_parser);
}
//----------------------------------------------------------------------------
// specify what to do with each parsed token; i.e. the token handler
function XML_startElement($parser, $name, $attrs = '')
{
     global $n_items;
     global $inventory;
     switch($name)
     { 
        case 'INVENTORY':
           $inventory = array(); 
           break;
         case 'ITEM':
           $inventory[ $n_items ] = array();
           foreach($attrs as $key => $value)
           {
              $inventory[ $n_items ][ strtolower($key) ] = $value;
           }
           $n_items++; 
           break;
      }
} 
//----------------------------------------------------------------------------
// function to handle the element's character data
// or: $char_data = preg_replace('/  */',' ',$data); (perform regex replacement)
function XML_data($parser, $data)
{
   global $n_items;
   $index = $n_items - 1;
   global $inventory;
   $char_data = trim($data);
   $key = "cdata";
   if($char_data) {
       $inventory[ $index ][ $key ] = $char_data;
   }
}
//----------------------------------------------------------------------------
// dump everything 
function dump_array() {
     global $n_items;
     global $inventory; 

     // a var_dump function
     echo substr(date('r'),0,16);
     print_r($inventory);   
     printf('number of items: %d',$n_items);
}
//----------------------------------------------------------------------------
// this function must be present even if empty
function XML_endElement($parser, $name) 
{ 
}

//----------------------------------------------------------------------------

// display a tabular list of item name, item description and item count
function report()
{
   global $n_items;
   global $inventory;
   $td = substr(date('r'),0,16);
   printf("<H3>INVENTORY REPORT</H3>Date: %s<p>",$td);
   printf("%-15s%-35s%-15s","Name","Description","Count"); 
   printf("\n<BR>");
   printf("%-15s%-35s%-15s","=====","============","====="); 
   printf("\n<BR>");
   $i = 0;
   $sum = 0;
   while ($i < $n_items){
      $nm = $inventory[$i][ "name" ]; 
      $dsc = $inventory[$i][ "description" ]; 
      $cnt = $inventory[$i][ "cdata" ]; 
      printf("%-15s%-35s%-15s", $nm, $dsc, $cnt); 
      printf("\n<BR>"); 
      $i += 1;
      $sum += $cnt;
   }
   printf("<BR>TOTAL: %d<BR>",$sum);
   echo "\nreport generated by d meyers\n";
}
?>
